### ISSUE TITLE
Strange behavior of -cbl option

### ISSUE THREAD

**Issue by elcamlost** [perltidy/perltidy#10]
Hi!

As far as I understand, **-ce** and **-cbl=map,sort,grep** options should allow for multiline cuddled-style Schwartzian transform.

Example from wikipedia in cuddled style.
```perl
@sorted = map {
    $_->[0]
} sort {
    $a->[1] <=> $b->[1] or $a->[0] cmp $b->[0] 
} map {
    [$_, length($_)]
} @unsorted;

```

**perltidy -st -wn -ce -cbl=sort,map,grep** for this snippet is
```perl
@sorted = map { $_->[0] } sort {
    $a->[1] <=> $b->[1] or $a->[0] cmp $b->[0] 
} map { [ $_, length($_) ] } @unsorted;
```

First line is containing two keywords. Even if I add new grep or map block on top, situation stays the same. First line contains whole first block, block keyword and opening curly brace.
And the same thing for last string. It's always containing list variable and last block.

Is it intended behavior? Can I do something to fix formatting here?

**Comment by shancock9** [comment]
It looks like this is a conflict between rules for "one-line blocks" and
the cuddled-else  style. The
relevant section of the manual is:

---

With few exceptions, perltidy retains existing one-line blocks, if it is
possible within the line-length
constraint, but it does not attempt to form new ones.  In other words,
perltidy will try to follow the one-line
block style of the input file.

If an existing one-line block is longer than the maximum line length,
however, it will be broken into multiple
lines.  When this happens, perltidy checks for and adds any optional
terminating semicolon (unless the -nasc
option is used) if the block is a code block.

The main exception is that perltidy will attempt to form new one-line
blocks following the keywords "map",
"eval", and "sort", because these code blocks are often small and most
clearly displayed in a single line.

One-line block rules can conflict with the cuddled-else option.  When the
cuddled-else option is used, perltidy
retains existing one-line blocks, even if they do not obey cuddled-else
formatting.

---

In the example, the first map block is so short that perltidy is forming a
one-line block.  If you add some
code to it as a test and rerun you will see that the cuddled style appears
okay.

I'm not sure how difficult this would be to change for the case that map is
declared to be a cuddled word, but I'll check.
Steve

**Comment by shancock9** [comment]
I've made an update which fixes this.

**Comment by shancock9** [comment]
Version 20190915 gives this result, which is better

@sorted = map {
    $_->[0]
} sort {
    $a->[1] <=> $b->[1] or $a->[0] cmp $b->[0]
} map { [ $_, length($_) ] } @unsorted;

The final map block is still on a single line though.

**Comment by shancock9** [comment]
version 20191203 now gives the desired result:
@sorted = map {
    $_->[0]
} sort {
    $a->[1] <=> $b->[1] or $a->[0] cmp $b->[0]
} map {
    [ $_, length($_) ]
} @unsorted;
