### ISSUE TITLE
Parentheses no longer line up

### ISSUE THREAD

**Issue by FractalBoy** [perltidy/perltidy#107]
My .perltidyrc contains:

```
-gnu
-csc
-l=200
```

I recently upgraded from v20210625 to v20220613, so I'm not sure when this was introduced. However, function calls with parameters that take up multiple lines are no longer formatted the same as they were before I upgraded. I'm not sure if this is intentional or a bug.

Before, the parentheses would line up, like:
```
my $var = func(
    param1 => 'param1'
    param2 => 'param2',
    code_ref => sub {
        my ($param) = @_;
        ...
    },
    param3 => 'param3'
              );
```

Now, the end parenthesis does not line up with the opening parenthesis, and instead stays at the beginning of the line (including any indentation, depending on the indent level)

```
my $var = func(
    param1 => 'param1'
    param2 => 'param2',
    code_ref => sub {
        my ($param) = @_;
        ...
    },
    param3 => 'param3
);
```

**Comment by shancock9** [comment]
Note that there is a missing comma after 'param1', so this will not format as shown.  I assume this was removed during editing.

This change is intentional, not a bug. What's happening is that the method of resolving conflicting constraints has changed.  The ``-lp`` style has some limitations which are listed in the manual, and in particular it is not able to handle the anonymous sub in the list. Consequently, the coding between the parens reverts to the standard indentation model.  In the older version of perltidy the closing paren still lined up with the opening paren, but this broke the indentation hierarchy. In the newer version, the closing paren is not allowed to be indented more than the previous lines, in order to maintain the indentation hierarchy.

This snippet illustrates the reason that the ``-xlp`` flag was developed.  The ``-xlp`` flag makes the ``-gnu`` style function as originally intended, but has to be explicitly included:


```
# perltidy -gnu -xlp -lpil='f('
my $var = func(
               param1   => 'param1',
               param2   => 'param2',
               code_ref => sub {
                   my ($param) = @_;
                   ...;
               },
               param3 => 'param3'
              );
```

I suggest also using the optional ``-lpil`` flag to control the types of containers to which this style is applied. The manual has details.

**Comment by FractalBoy** [comment]
Okay, thank you. I will discuss with my team as to whether we want to add `-xlp` and `-lpil` or just stick to the default `-gnu` settings.
