### ISSUE TITLE
)) ) vs. )))

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#120]
```
$aqx->appendChild(
    $parser->parse_balanced_chunk(qq(<param name="skv">$skv</param>)) );

```
Are you sure you want the ")) )" as default instead of ")))"?

Sure, it can probably be explained as matching something invisible on the left.

**Comment by shancock9** [comment]
The default is a space; the space can be removed with -pt=2.  Note that the inner paren of the triplet ``)) )`` here is a quote terminator and could have been many other characters as well, but the default does not depend on it. 

In general,  default values are not changed because that would change a lot of existing formatting.

**Comment by jidanni** [comment]
I am thinking, perhaps it should recognize that it is already on a new line, so there is nothing on the left that it can look symmetrical with, so it might as well do like it did with the other )'s, piling them together.

Wait. I see. You are saying that the qq() is a special case... Ah, OK. Closing.
