### ISSUE TITLE
Format only a region of a file

### ISSUE THREAD

**Issue by lassik** [perltidy/perltidy#122]
Would it be possible to add command line flag(s) that let the user format only part of a file? The whole file would be passed to stdin (or read from a file) and would be output as-is, except that the code between the given line numbers or file offsets would be tidied.

This would help implement a reliable "format region" command in text editors.

For reference, similar `clang-format` flags from https://clang.llvm.org/docs/ClangFormat.html:

```
  --cursor=<uint>            - The position of the cursor when invoking
                               clang-format from an editor integration
```

```
  --offset=<uint>            - Format a range starting at this byte offset.
                               Multiple ranges can be formatted by specifying
                               several -offset and -length pairs.
                               Can only be used with one input file.
  --length=<uint>            - Format a range of this length (in bytes).
                               Multiple ranges can be formatted by specifying
                               several -offset and -length pairs.
                               When only a single -offset is specified without
                               -length, clang-format will format up to the end
                               of the file.
                               Can only be used with one input file.
```

```
  --lines=<string>           - <start line>:<end line> - format a range of
                               lines (both 1-based).
                               Multiple ranges can be formatted by specifying
                               several -lines arguments.
                               Can't be used with -offset and -length.
                               Can only be used with one input file.
```

Another popular formatter `prettier` also has similar flags.

**Comment by shancock9** [comment]
A tentative new parameter is available for testing in tagged version 20230707.01 at https://github.com/perltidy/perltidy/tags. The description is as follows

### Formatting a Limited Range of Lines

A command **--line-range-tidy=n1:n2** is available to pass just a selected range
of lines to perltidy.  This is command is mainly of interest to interactive
code editors.  When it is used, just the selected range of lines are passed
through the perltidy tokenizer and formatter, so they need to contain a
complete statement or balanced container.  Otherwise, a syntax error will occur
and the code will be returned unformatted.  There are a couple of limitations
on the use of this command: (1) it may not be applied to multiple files, and
(2) it only applies to code tidying and not, for example, html formatting.

- **-lrt=n1:n2**,  **--line-range-tidy=n1:n2**

    The range of lines is specified by integers **n1** and **n2**, where **n1** is the first line number to be formatted (start counting with 1) and **n2** is the last line number to be formatted.  If **n2** is not given, or exceeds the actual number of lines, then formatting continues to the end of the file. 

    Examples:

        -line-range-tidy=43:109      # tidy lines 43 through 109
        -line-range-tidy=' 43 : 109' # tidy lines 43 through 109 (spaces ok in quotes)
        -line-range-tidy=1:          # tidy all lines
        -line-range-tidy=0:90        # ERROR (n1 must be >= 1)

**Comment by lassik** [comment]
Awesome! Thank you very much. That was very quick.

@tsilvap Can you try it?

**Comment by tsilvap** [comment]
I tried it out to format some line ranges in a few of my files and it worked as I expected. Thank you @shancock9 and @lassik.

**Comment by shancock9** [comment]
This update is in CPAN version 20230909, so I'll close this now.
