### ISSUE TITLE
Whitespace being added between subroutine name and argument list

### ISSUE THREAD

**Issue by willroofe** [perltidy/perltidy#125]
When I have a subroutine (or method) with an argument list, perltidy seems insistent on adding whitespace between the subroutine's name and the opening parentheses.

For example, `sub Add($x, $y)` becomes `sub Add ($x, $y)`.

This issue does not occur when the argument list is empty and the `-spp` switch (which seemed to be the closest match to addressing my problem) doesn't seem to make any difference.

**Comment by shancock9** [comment]
The flag ``--space-prototype-paren``, or ``-spp``, works when the parens are empty because in that case the parens are tokenized as a prototype.  But the parens in ``sub Add ($x, $y)`` are tokenized as a signature, so the ``-spp`` flag does not apply.

So it looks like we need a new flag, maybe ``--space-signature-paren=n``, analogous to ``-space-prototype-paren=n``, to control this. It should be a simple update.

Thanks for reporting this.

**Comment by shancock9** [comment]
Tagged version 20230912.03 at  https://github.com/perltidy/perltidy/tags 
has a new flag --space-signature-paren=n, or -ssp=n, to handle this.  You would use -ssp=0 to eliminate the space.

**Comment by willroofe** [comment]
Just gave it # a try, worked an absolute treat! Thank you so much.
