### ISSUE TITLE
--make-maximum-line-length-also-affect-comments-too

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#127]
Emacs' "fill-paragraph" etc. commands can make e.g.,
```
# Corner node names: we choose "Bureau of Land Management Geographic
# Coordinate Database (GCDB) Publication Point IDs" format, e.g.,
# `600100`, referring to the southwest corner of section 36.
```
along with (set-fill-column 22), into
```
# Corner node names:
# we choose "Bureau of
# Land Management
# Geographic
# Coordinate Database
# (GCDB) Publication
# Point IDs" format,
# e.g., `600100`,
# referring to the
# southwest corner of
# section 36.
```
So it would be great if perltidy
had an additional flag
- --comment-maximum-line-length
like
- --maximum-line-length
Or maybe a
- --comment-maximum-line-length=maximum-line-length
to lock them together.
Or maybe
- --make-maximum-line-length-also-affect-comments-too

**Comment by shancock9** [comment]
The option is not in perltidy itself because fully automated implementation could lead to 
disaster by irreversibly reformatting comments should not be reformatted. These include
commented code, organization boilerplate statements, control comments, artwork, etc.

But there is an interactive program named ``perlcomment.pl`` in the ``examples/`` folder of 
the perltidy distribution which can do this, see 

http://github.com/perltidy/perltidy/blob/master/examples/perlcomment.pl

The command would be:

```
perlcomment.pl -l22 infile >outfile
```

This program walks through a file and uses Perl::Tidy to locate groups of comments. 
It uses Text::Autoformat to reformat the comments to the desired line length, and asks the user 
if the change should be accepted.

The indentation which is assumed for blocks of comments is whatever the indentation is in the
input file.  A potential problem is that if the input file has very long comments which have 
been out-dented, this may not give the desired result. This problem can be avoided by doing a 
preliminary formatting pass with perltidy which includes the parameter 
``--ignore-side-comment-lengths`` (``-iscl``).

**Comment by jidanni** [comment]
Ah, OK. Maybe the perltidy man page should mention something about the danger and alternative method.

I mean otherwise "people might think 'odd, the man page has so much about comments, but never
gets around to how to keep them slim and trim.'"
