### ISSUE TITLE
Remembering the alignment of consecutive elements

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#130]
Using `-l=79 -vil='=>'`, instead of having:

```
$code = $sock->search_group_all(
    groupname => $groupname,
    low       => 1,
    cols      => search_col_arrived | search_col_expires | search_col_token
      | search_col_overview,
    readsize => 0xFFFFF,
    errmsg   => $errmsg,
);
```

would it be possible to align all the hash pairs? (that is to say adding a space for the last 2 entries)

Also, is there an option to for instance have:

```
    cols      => search_col_arrived | search_col_expires | search_col_token
                   | search_col_overview,
```

**Comment by Julien-Elie** [comment]
Thanks, understood.

**Comment by shancock9** [comment]
I looked at the possibility of restarting a vertical alignment following a break
due to a long line, as in the example.  In this particular example it would work
well, but in general it could also produce some poor formatting, especially in
long lists. The main problem is that in vertical alignment, as we go down an
unbroken list, the => always moves to the right to accommodate the longest item
in the list so far, never to the left. So if a long list of unbroken alignments
has short terms near the bottom, their => may be spaced far to the right due to
the longest term previously seen in the list. This does not look good if one is
just viewing the bottom of the list.  This is a general problem with vertical
alignment, and the only solution is to make vertical alignment "fragile", so
that it breaks whenever possible.  Allowing an alignment to restart would
prevent this from happening, thus producing some poor formatting in long lists.

**Comment by Julien-Elie** [comment]
Ok, thanks for your answer.  I understand.
