### ISSUE TITLE
Removal of unnecessary hashref arrows

### ISSUE THREAD

**Issue by dboehmer** [perltidy/perltidy#133]
I find that new Perl developers use this syntax

    $hashref->{a}->{b}

rather than this

    $hashref->{a}{b}

I find the latter much more appealing. I consider automatically removing or rejecting introduction of unnecessary arrow operators to access nested hash keys. Is this possible with perltidy or might this be solvable with a perlcritic rule?

**Comment by oalders** [comment]
This kind of thing could be solved by adding a rule to https://metacpan.org/dist/App-PerlNitpick

**Comment by shancock9** [comment]
The App:PerlNitpick approach looks interesting. Thanks @oalders for pointing that out.

This should also be possible in perltidy, but I need to think about it.  
I wrote a patch for perltidy just to test this idea and it worked ok. 
The programming is straightforward but there are a number of issues to consider.

1. If there is a parameter for deleting pointers, then ideally there should 
be one to put them back.

2. Some controls need to be designed to make it possible to add or delete
pointers between various combinations of hash key braces and array index
brackets.

3. A message should be written to the error file whenever this is done to
warn the user to carefully check the result.

4. Some thought needs to go into insuring that this operation is only done
when it is safe to do so. There are some potential pitfalls to be avoided.

**Comment by shancock9** [comment]
I added a parameter **--delete-interbracket-arrows**, or **-dia**, to perltidy which will
delete these arrows.  A related parameter **--add-interbracket-arrows**, or **-aia**, can
add them back.  It was hard to come up with a good name for these parameters. I 
settled on 'interbracket arrows', which is not great but captures the idea.

This option is available for testing in tagged version 20240202.01 at

https://github.com/perltidy/perltidy/tags

The updated manual section describes additional controls:

https://github.com/perltidy/perltidy/commit/c3023c07aa07f73b5e7672c871b62dd60405e0c2

I haven't found any bugs in testing, but use it with caution since it is new.

**Comment by dboehmer** [comment]
I tested the version from tag 20240202.01 with `--delete-interbracket-arrows` and it worked fine! :+1: I also find the name quite good.

**Comment by shancock9** [comment]
Version 20240511 at CPAN has this update.
