### ISSUE TITLE
Not tidy after running perltidy

### ISSUE THREAD

**Issue by rlauer6** [perltidy/perltidy#134]
Run the latest version of perltidy with the attached `.perltidyrc` - after running first time, perltidy reports that the file is still not tidy and removes 2 spaces from the array's first element.

[perlcriticrc.txt](https://github.com/perltidy/perltidy/files/14570912/perlcriticrc.txt)

Before:

```
sub foo {
    my($self, $clientKey, $systemKey) = @_;

    $q->do(
        q{
          Something
        },
        [
            $clientKey,
            $systemKey,
        ],
    );

    
    return;
}
```

Pass 1

```
sub foo {
    my ( $self, $clientKey, $systemKey ) = @_;

    $q->do(
        q{
          Something
        },
        [   $clientKey,
            $systemKey,
        ],
    );

    $result = $q->cachedResults()->[0];

    return;
}
```

Pass 2
```
sub foo {
    my ( $self, $clientKey, $systemKey ) = @_;

    $q->do(
        q{
          Something
        },
        [ $clientKey,
            $systemKey,
        ],
    );

    $result = $q->cachedResults()->[0];

    return;
}
```

**Comment by shancock9** [comment]
Thanks for the note. It looks like you attached the ``perlcritic`` configuration file instead of 
the ``perltidy`` configuration file, but I can reproduce this by assuming default parameters for
the initial script and then adding ``-vt=1`` or ``-vt=2`` (vertical tightness) in the second and third.

There are a couple of issues to mention:

First, when changing formatting parameters. it can take an extra iteration to reach a stable state, which happens
to be the result after pass 2. This can be avoided by telling ``perltidy`` to converge with the ``-conv`` parameter.
This is not the default because it can double the run time and is not usually necessary after parameters
have been fixed. But if run time is not an issue then it is a good idea to add it. So adding ``-conv`` should solve 
the problem with ``perlcritic``.

Second, regarding the actual formatting, the result after pass 1 is nicer than the stable state reached in
pass 2.  This particular small list of two items is an edge case for the ``-vt`` option when it makes a certain
decision regarding line breaks. I will take a look at it and see if it might be improved.

**Comment by shancock9** [comment]
Version 20250511 at CPAN has an update to converge to the result of Pass 1 in a single step.
