### ISSUE TITLE
Unexpected/odd mixed if/unless modifier alignment

### ISSUE THREAD

**Issue by tlhackque** [perltidy/perltidy#135]
I noticed that the alignment of `if` and `unless` statement modifiers behaves unexpectedly if they are mixed.

None of these are a big deal, but as you keep improving Perl::Tidy, I thought I should mention them.

Here are some code snippets that illustrate my observations. 

Result:
```perl
@ns      = split( /, ?/, join( ',', @ns ) );
@cnames  = split( /, ?/, join( ',', @cnames ) );
$recurse = 1       unless( defined $recurse );
$port    = 53      unless( defined $port );
$srcport = 0       unless( defined $srcport );
$ttl     = 30 * 60 unless( defined $ttl );
$hash    = 32 if( defined $hash && $hash <= 0 );
$hash    = 63 if( defined $hash && $hash > 63 );
$unique  = 1 unless( defined $hash || defined $unique );
$unique ||= $hash;
```

If I demorgan the `if`s, I get the more visually pleasing but less comprehensible:
```perl
@ns      = split( /, ?/, join( ',', @ns ) );
@cnames  = split( /, ?/, join( ',', @cnames ) );
$recurse = 1       unless( defined $recurse );
$port    = 53      unless( defined $port );
$srcport = 0       unless( defined $srcport );
$ttl     = 30 * 60 unless( defined $ttl );
$hash    = 32      unless( !defined $hash || $hash > 0 );
$hash    = 63      unless( !defined $hash || $hash <= 63 );
$unique  = 1       unless( defined $hash  || defined $unique );
$unique ||= $hash;
```
So it seems to me that `if` and `unless` modifiers ought to be considered equivalent for alignment purposes.

Whether the `=` of the `||=` ought to align with those above is another minor nit.  It does seem to start a new alignment group, since if I move the array assignments to the bottom (where they started before I tried to persuade Perl::Tidy to my way of thinking), the result is
```perl
$recurse = 1       unless( defined $recurse );
$port    = 53      unless( defined $port );
$srcport = 0       unless( defined $srcport );
$ttl     = 30 * 60 unless( defined $ttl );
$hash    = 32 if( defined $hash && $hash <= 0 );
$hash    = 63 if( defined $hash && $hash > 63 );
$unique  = 1 unless( defined $hash || defined $unique );
$unique ||= $hash;
@ns     = split( /, ?/, join( ',', @ns ) );
@cnames = split( /, ?/, join( ',', @cnames ) );
```
The semantics of this defaulting scheme are sensitive to ordering, so there's a limit to what juggling the code can do.

```sh
 # modver Perl::Tidy
Perl::Tidy 20240202
```

[.perltidyrc](https://github.com/perltidy/perltidy/files/14721521/dotperltidyrc.txt)

As always, thanks for your work on this module.  Perl certainly doesn't make it easy.

**Comment by shancock9** [comment]
Thanks for the note.  There is actually a parameter to align ``if`` and ``unless``,
namely ``--valign-if-unless``, or ``-viu``:

```
# perltidy -viu
@ns      = split( /, ?/, join( ',', @ns ) );
@cnames  = split( /, ?/, join( ',', @cnames ) );
$recurse = 1       unless ( defined $recurse );
$port    = 53      unless ( defined $port );
$srcport = 0       unless ( defined $srcport );
$ttl     = 30 * 60 unless ( defined $ttl );
$hash    = 32      if ( defined $hash && $hash <= 0 );
$hash    = 63      if ( defined $hash && $hash > 63 );
$unique  = 1       unless ( defined $hash || defined $unique );
$unique ||= $hash;
```

It was activated in git #116, but it was not made the default because it would have changed
a lot of existing formatting.  So it is hidden in the manual.

Regarding alignment of ``=`` and ``||=``, or even ``&&=`` or ``+=``,
unfortunately the logic to do this is quite complicated.  For example, if a
long list of lines with '=' alignments has a single '||=' somewhere, then all
of those ``=`` lines would need to add two additional spaces of padding to get
all the ``=`` signs to align and look good.  And if there were a ``+=`` in the list,
then it would have to add one space.  But some of the ``=`` lines might then
hit the line length limit and not be able to add spaces, so that situation
needs to be handled somehow. So basically, suddenly everything gets
interconnected in a rather complex way, for relatively little benefit.

This problem is avoided in the alignment of ``if`` and ``unless``, which also
have different lengths, by not also aligning the following opening parens.

Thanks again for the suggestions.

**Comment by tlhackque** [comment]
I missed that option.  Thanks.  I've added it to all my `.perltidyrc` files!

It seems to me that a brute force answer to the `=`-containing operators would be to treat them all as 3 characters wide, always.
E.g. when you tokenize the input, replace them with a token containing 0, 1, or 2 un-removable spaces on their left sides.  Then line padding & folding would, I guess/hope work as it would currently for code that only used, say, ||=.  A little extra space before an operator doesn't hurt, right?   `-weo-` (--widen-equals-operators) seems unused...

```
    0 => '||=', '&&=', '<<=', ...
    1 => '_+=','_ -=', '_/=', '_%=', ...
    2 => '__='
```

Where for visual clarity here, '_' means 'space (or maybe even IS the token).  The commas line up neatly above.

For extra points, I suppose that a sequence of these 1-2 widened tokens of equal width that comprise an alignment block could be replaced with narrower ones.  Removing spaces doesn't cause the same cascades as adding them.  I think.  

If all that's true, the same trick could be applied to if & unless, which would then allow aligning the opening parens.  Including the opening paren in the token might help.  e.g. tokenize 'if' as if it was 'if____(',  (or 'if_____(' for the 'if (' style.  Similarly, tokenize 'unless" as 'unless(' or 'unless ('

But then, I'm far from the code, and things probably look different up close.  Or maybe a different perspective helps.

In any case thanks for your long-term commitment to this tool.

**Comment by shancock9** [comment]
Adding extra spaces to certain tokens would unfortunately impact a lot of
existing code. As just one example, if a user requested that line breaks occur
before an equals, then there would need to be new code to check to see if the
equals had extra spaces, and if so remove them, since otherwise the line
indentation would be incorrect.

But a possible even simpler approach would be to add an option to align any
assignment operator without trying to also align the ``=``. This can be done
with a simple coding change (just one line). Then, as an optional second step
for groups of aligned tokens, remove padding spaces from the left of
multi-character assignment tokens if enough spaces exist. This is more
complex to implement but should be possible.

As a test, I tentatively implemented the first part of this and ran it on
a large amount of code.  Overall, I think the results were an improvement
in clarity, even without aligning the equals signs.  The main benefit 
was that a single token such as ``-=`` no longer interrupted the
overall alignment. For example, here is the default formatting of a certain block:

```
    @tmp = reverse split( /\//, $date );
    $tmp[1] -= 1;
    $tmp[2] -= 1900;
    $epoch = timelocal( 0, 0, 0, @tmp );
    $$dow_ref{$date} = $day = ( localtime $epoch )[6];
```

Here is the same code formatted with the test patch:

```
    @tmp             = reverse split( /\//, $date );
    $tmp[1]          -= 1;
    $tmp[2]          -= 1900;
    $epoch           = timelocal( 0, 0, 0, @tmp );
    $$dow_ref{$date} = $day = ( localtime $epoch )[6];
```

In this particular case, it would be possible to remove a space before the
``-=`` lines just before outputting them to get a small further improvement,
but the main benefit is not allowing the ``-=`` operators to interrupt the
overall alignment.

Another benefit that I saw was that sometimes new additional trailing
alignments (such as trailing if statements or ternary operators) could be made
with this change. 

I did see a couple of cases where formatting got worse, but overall I would say
it improved.  So I will look into this as a possible future update. Thanks
again for the ideas.

**Comment by tlhackque** [comment]
I agree: that does improve your example a lot.  It resonates as a common case, since I do re-arrange things to avoid breaking alignment blocks.  Obviously, I don't really understand the complexities of what you face.  But I'm glad that I stimulated a new thought nonetheless.

FWIW, if the wide token idea works in enough places & the ones where it doesn't are associated with a few specific options (as in your example), there's always the choice to turn wide tokens off when hard-to-handle options are selected.   ("If you want ice-ream, I'll take away the cake.") If it turned out to be a hit, you could work on the restrictions when time was available and if the mood struck.  Or not.  

But if your "simple" change continues to show a sizeable benefit and the work doesn't cascade, obviously it's the better choice.

I won't push further; not enough data or expertise.  It was just an idea.  A group I was in long ago had an apropos motto: "Everyone has a vote on an idea.  The person doing 90% of the work has 90% of the votes."  Here, I'm doing 0%...

I don't think it's anything special, but the code that started this thread is available if context would help.  `acme_token_check` in [my certtools repo](https://github.com/tlhackque/certtools).

Probably not worth a more than a glance, but I noticed a minor case of seemingly unnecessary folding (see line 434/5); here the assignment using Digest::SHA strands the `'.';` after the `substr`.

```perl
    foreach my $c ( @cnames ) {
        my $zid = '';
        if( $unique ) {
            if( $hash ) {
                $zid = substr(
                           Digest::SHA::sha256_hex( $zid . int( rand( 2_000_000_000 ) ) ),
                           0, $hash ) .
                    '.';
            } else {
                $zid = "${c}${zone}";
            }
        }
    }
```

**Comment by shancock9** [comment]
Tagged version 20240202.03 at https://github.com/perltidy/perltidy/tags has a
new option ``--valign-wide-equals``, or ``-vwe`` which implements the alignment
option that we've been discussing. 

The implementation is clean and does not interfere with any other options.
There is change in a single code line which causes all of the wide equals to
align, and there is a new subroutine which gets switched on by this option to
add one or two spaces where needed, just before a line is output, in order to
get the equals signs aligned.  If a line length would be exceeded by adding the
space, then it is not added. But I saw very few cases where this happened when
I tested it on a lot of existing code.

The results are almost always an improvement in readability. For example,
I found the following example when testing this on perltidy itself:

```
            $str .= SPACE x $total_pad_count;
            $str_len += $total_pad_count;
            $total_pad_count = 0;
            $str .= $rfields->[$j];
            $str_len += $rfield_lengths->[$j];
```

which becomes with ``-vwe``:

```
            $str             .= SPACE x $total_pad_count;
            $str_len         += $total_pad_count;
            $total_pad_count  = 0;
            $str             .= $rfields->[$j];
            $str_len         += $rfield_lengths->[$j];
```

This is much easier on the eyes. For now, the ``-vwe`` option is not the default
because this would change a lot of existing formatting.

This version also has an update to avoid stranding a small concatenated
terminal quote as in your example.

Thanks again for the suggestion, I think this is a nice new feature.

**Comment by tlhackque** [comment]
Looks good.  Thanks for the quick work.

I tried it on `acme_token_check`, where it made some improvements.  Noticed a couple of nits, just FYI -  I'm happy.

Not sure why it un-aligned the `if` & `unless` below (almost the same snippet as before.)

```perl
@ns        = split( /, ?/, join( ',', @ns ) );
@cnames    = split( /, ?/, join( ',', @cnames ) );
$recurse   = 1       unless( defined $recurse );
$port      = 53      unless( defined $port );
$srcport   = 0       unless( defined $srcport );
$ttl       = 30 * 60 unless( defined $ttl );
$hash      = 32    if( defined $hash && $hash <= 0 );
$hash      = 63    if( defined $hash && $hash > 63 );
$unique    = 1     unless( defined $hash || defined $unique );
$unique  ||= $hash;
```
Or this (a bit further down); it moved the last two assignments a space to the right, but didn't find the block.  Maybe because of the `my`?

```perl
if( @cnames || $czone ) {
    my $created = 0;
    @cnames = '.' unless( @cnames );
    my %cn = map { s/[.*]$//; $_ .= '.' if( length ); ( $_ => 1 ) } @cnames;
    @cnames  = keys %cn;
    $czone  .= '.' unless( $czone =~ /\.$/ );

}
```
```diff
perltidy -vwe acme_token_check
diff -U5 acme_token_check acme_token_check.tdy
--- acme_token_check    2024-03-23 18:36:57.000000000 -0400
+++ acme_token_check.tdy        2024-03-25 22:57:44.000000000 -0400
@@ -164,29 +164,29 @@
             join( '-', ( $VERSION =~ /([[:xdigit:]]{4})/g )[ -4 .. -1 ] ), $copyright );
     exit;
 }

 if( defined $rectype ) {
-    $remove ||= 0;
-    $rectype |= $remove;
+    $remove  ||= 0;
+    $rectype  |= $remove;
 } elsif( defined $remove ) {
     $rectype = $remove;
 } else {
     $rectype = REC_TXT;
     $remove  = 0;
 }

-@ns      = split( /, ?/, join( ',', @ns ) );
-@cnames  = split( /, ?/, join( ',', @cnames ) );
-$recurse = 1       unless( defined $recurse );
-$port    = 53      unless( defined $port );
-$srcport = 0       unless( defined $srcport );
-$ttl     = 30 * 60 unless( defined $ttl );
-$hash    = 32      if( defined $hash && $hash <= 0 );
-$hash    = 63      if( defined $hash && $hash > 63 );
-$unique  = 1       unless( defined $hash || defined $unique );
-$unique ||= $hash;
+@ns        = split( /, ?/, join( ',', @ns ) );
+@cnames    = split( /, ?/, join( ',', @cnames ) );
+$recurse   = 1       unless( defined $recurse );
+$port      = 53      unless( defined $port );
+$srcport   = 0       unless( defined $srcport );
+$ttl       = 30 * 60 unless( defined $ttl );
+$hash      = 32    if( defined $hash && $hash <= 0 );
+$hash      = 63    if( defined $hash && $hash > 63 );
+$unique    = 1     unless( defined $hash || defined $unique );
+$unique  ||= $hash;

 # Get a list of zones from named's statistics channel if specified & no command line zones

 if( !@ARGV && $named ) {
     require LWP::Simple;
@@ -255,12 +255,12 @@
         };
     }
     my $created = 0;
     @cnames = '.' unless( @cnames );
     my %cn = map { s/[.*]$//; $_ .= '.' if( length ); ( $_ => 1 ) } @cnames;
-    @cnames = keys %cn;
-    $czone .= '.' unless( $czone =~ /\.$/ );
+    @cnames  = keys %cn;
+    $czone  .= '.' unless( $czone =~ /\.$/ );

     foreach my $zone ( keys %zones ) {
         my $nc = generateCnames( $zone, $czone );
         $created += $nc;
     }
@@ -429,12 +429,11 @@
         my $zid = '';
         if( $unique ) {
             if( $hash ) {
                 $zid = substr(
                            Digest::SHA::sha256_hex( $zid . int( rand( 2_000_000_000 ) ) ),
-                           0, $hash ) .
-                    '.';
+                           0, $hash ) . '.';
             } else {
                 $zid = "${c}${zone}";
             }
         }
         my $rr = Net::DNS::RR->new( name  => "_acme-challenge.${c}${zone}",
```

**Comment by shancock9** [comment]
The first problem is related to the fact that the two ``if`` lines have third common alignment at their ``&&`` tokens. It is not related to ``if`` vs ``unless``. This put them in a separate alignment group which did not pick up the two additional shift spaces. This should be fixable.

The other issue is due to a basic rule that lines with a leading ``my`` generally do not get aligned with lines without a ``my``.

**Comment by shancock9** [comment]
Version 20240511 at CPAN has these updates, including a fix for the last item.

**Comment by tlhackque** [comment]
Thanks again for all your work!
