### ISSUE TITLE
Exclude operator for line break completely

### ISSUE THREAD

**Issue by fyousef-intel** [perltidy/perltidy#136]
Is there a way to exclude an operator from a line break?

For example, I don't want any line breaks on a dot.
According to the documentation:
"**to break before all operators except an = one could use --bbao -wba='='**"

However, if I use:
`-bbao -wba='.'`

I still get line breaks on the dot when the line is longer than the maximum-line-length.
Is there a way to disable that? Even if it means that the line would remain longer than the maximum-line-length?

Example:
```
my $word = aaaaaaaaaaaaaaaaaa.bbbbbbbbbbbbbbb.cccccccccccccccc.dddddddddd.eeeeeeeeeeeeeeeee.fffffffffffff.gggggggggggggg;
```
maximum-line-length set to 120.

Line would be broken to:
```
my $word =
    aaaaaaaaaaaaaaaaaa
  . bbbbbbbbbbbbbbb
  . cccccccccccccccc
  . dddddddddd
  . eeeeeeeeeeeeeeeee
  . fffffffffffff
  . gggggggggggggggggg;
```
NOTE: I have a Perl-based language, which supports an API such as 'keyword1.keyword2.keyword3', where I don't want any line breaks. A dot for me is not always a concatenation operation.

**Comment by shancock9** [comment]
I don't see a way to do this right now. The line length limit has very high priority, 
and is mainly allowed to be exceeded in these cases:

* a very long quote
* a very long identifier
* --ignore-side-comment-lengths
* --indent-only
* code fenced-off from formatting with #<<< and #>>> 

It might be possible to add a parameter for this, but I would need to know
more about the syntax. For example, in the example, the terms 
like 'aaaaaaaaaaaaaaaaa' parse to bare words. Is this always the case?
If that were true, then one possibility, for example, would be to add a 
control which implemented a rule that a sequence of bare words separated 
by a ``.`` would be combined into a single identifier, or quote, thereby 
remaining intact during formatting.

**Comment by fyousef-intel** [comment]
Thanks for the quick response!
The use cases are similar to the following:
There's an initial string, for example "test", or "state", followed by a dot.
Anything that comes after it from variables, brackets, dots, keywords is not expected to have spaces.
Here are a few examples:
- `state.x.y[0x1]`
- `state.${variable1}.${variables2}_suffix`
- `test.project[$name].date`

Currently, my workaround is to set the max-line-length to 0, and run a 'cleanup' script after the formatter which would locate these cases and remove the spaces surrounding the dots. The reason behind that is because I do want the concatenation operator to be surrounded by spaces, but not the saved keywords.

Please let me know if you need any additional details.

**Comment by shancock9** [comment]
A difficulty with trying to do this within perltidy is that, even if line
breaks and spaces are controlled at ``.`` operators, perltidy will still try to
break something like ``[$name]`` if it exceeds the line length limit, for example 

```
    ## perltidy -l=10
    test.project [
        $name
    ].date;
```

A better way to handle this may be by using a prefilter and postfilter.  The
current workaround is a postfilter, but adding a prefilter would allow normal
formatting without the need for ``l=0``.

The prefilter would look for these special strings, consisting of a '.' without
spaces, preceded by a bareword. It would then look forward to the next space or
newline in the text, and place that text within a quote which is unique, such as

```
    q<state.${variable1}.${variables2}.suffix>
```
or

```
    q|state.${variable1}.${variables2}.suffix|
```

or even

```
    q>state.${variable1}.${variables2}.suffix>
```

It would have to be careful that the syntax remains correct, by ending the
quote at the end of the final word rather than including any terminating
semicolon or comma, for example. 

Perltidy would run as usual, treating these as quoted strings, so they 
are written out verbatim. To keep them from being outdented, the parameter
``-no-outdent-long-quotes`` could be used

The postfilter would then just have to find and remove the quote marks.

Prefilters and postfilters can be passed as subs to perltidy, or the filtering
can be done separately by the calling program. Some examples of calling
perltidy as a module in this way are:

https://github.com/perltidy/perltidy/tree/master/examples

An example which passes filters to perltidy is ``filter_example.pl``

https://github.com/perltidy/perltidy/blob/master/examples/filter_example.pl

**Comment by fyousef-intel** [comment]
This is a great suggestion!
Thank you, this works perfectly for me.

**Comment by shancock9** [comment]
Great, good luck with your project.
