### ISSUE TITLE
-i=n and -ci=n together give double the indentation

### ISSUE THREAD

**Issue by fyousef-intel** [perltidy/perltidy#137]
Given the following subroutine call:
```
generate_error(msg => "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
```

I am using the PerlTidy flags:
1. --indent-columns=4
2. --continuation-indentation=4
3. --maximum-line-length=120

The result is:
```
generate_error(msg =>
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
);
```
Meaning, we get 4 spaces due to 'indent-columns' and another 4 due to 'continuation-indentation'.
Is this the expected behavior of PerlTidy?
I would've thought that we'd get only 4 in such a case, as it's either a new line, or a continuation of the previous line, not both.
If there a way to work around it?
I tried using -lp -vt=1, but that affects many other things that I don't want to change.

**Comment by shancock9** [comment]
The basic indentation formula gives ``-i`` spaces for being within containing parens or braces, plus ``-ci`` 
spaces for not being the first token in a term. This makes everything fit together regardless of complexity, 
and is completely independent of line break location.  But the result can be tweaked in special cases to 
improve appearance.

Here is how the indentation is reached in this particular case. The indentation starts as

```
generate_error(
    msg =>
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
);
```

If there were another item in the list, or it were more complex, this would be the final result.

But a later stage of processing, which looks for simplifications, notices the simplicity and joins 
the first two lines, giving the more compact result

```
generate_error( msg =>
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
);
```

This is the end result in this case, and it still follows the basic indentation formula.

In this particular case it would be reasonable to remove the ``-ci`` spaces from the quote, since it is completely contained in parens.

I'll look into adding a patch to do that.

**Comment by shancock9** [comment]
A new parameter, -mci or --minimize-continuation-indentation, can be set
to remove the extra spaces for cases like this. It is in tagged version 20240202.06 at

https://github.com/perltidy/perltidy/tags

and will be in the next release to CPAN, about 1 month from now.  

This parameter is currently off by default.  Testing shows that this issue mainly 
arises in code which has very long quoted strings and uses the -nolq flag to indent them,
as in this example.

**Comment by fyousef-intel** [comment]
Thank you for the support! This is exactly what I needed :)
