### ISSUE TITLE
Always indent before and after keyword

### ISSUE THREAD

**Issue by abeverley** [perltidy/perltidy#150]
I am wondering if there is a way to specify a keyword that is always indented before and after?

For example, if starting with this code:
````
$csv->combine($row->{id}, $row->{user}->{text}, $row->{type}, $row->{datetime}, $row->{description})
    or error __x "An error occurred producing the CSV headings: {err}",
        err => $csv->error_input;
````
It becomes this:
```
$csv->combine($row->{id}, $row->{user}->{text},
    $row->{type}, $row->{datetime}, $row->{description})
    or error __x "An error occurred producing the CSV headings: {err}",
    err => $csv->error_input;
```
But I would prefer it to be this (indent on the line before and after the `or`):
```
$csv->combine($row->{id}, $row->{user}->{text},
    $row->{type}, $row->{datetime}, $row->{description})
        or error __x "An error occurred producing the CSV headings: {err}",
            err => $csv->error_input;
```
Many thanks.

**Comment by shancock9** [comment]
There isn't a way to do this with the existing parameters, and significant
difficulties would be encountered in trying to implement this. The problem is
that the rule would have to handle arbitrarily complex statements.  Just as an
example, if we replace ``$csv->error_input`` with a long anonymous sub
definition, which itself had some 'or's, things get really complicated because
we would have to propagate all extra indentation down until we find an
appropriate end.

In this particular example, an alternate way to show the structure would be to
use the default value --continuation-indentation=2, rather than 4, and put
parens around the second parameter list. This would give

```
# -ci=2 with parens
$csv->combine( $row->{id}, $row->{user}->{text},
    $row->{type}, $row->{datetime}, $row->{description} )
  or error( __x "An error occurred producing the CSV headings: {err}",
    err => $csv->error_input );
```

**Comment by abeverley** [comment]
Thanks for the quick reply Steve, much appreciated. I can see what you mean as to how this could get complicated. Thanks also for the suggestion - I made everything 4-space indentations originally, just so that it was more "compatible" when formatting manually using a 4-space tab in an editor, but that might be a good option.
