### ISSUE TITLE
Better wrapping of arithmetic operations

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#152]
Would it be possible to follow usual arithmetic conventions and break lines at other places than `/` or `*` when there's enough room for it)?

For instance, instead of:

```
$poly->addPt(
    $marginl + $i * $w - $k - $shx,
    $ymax - $marginb - $jval
      / $factor
      * ($ymax - $marginb - $margint - $shy)
      / $max,
);
```

it would be better readable as:

```
$poly->addPt(
    $marginl + $i * $w - $k - $shx,
    $ymax - $marginb - $jval / $factor
      * ($ymax - $marginb - $margint - $shy)
      / $max,
);
```

or:

```
$poly->addPt(
    $marginl + $i * $w - $k - $shx,
    $ymax - $marginb
      - $jval / $factor
      * ($ymax - $marginb - $margint - $shy)
      / $max,
);
```

FWIW, I see that clang-format (for C) even adds another layer of indentation for the last `*` and `-` inside the parentheses.  Though not valid C code, clang-format would reformat it this way:

```
$poly->addPt(
    $marginl + $i * $w - $k - $shx,
    $ymax - $marginb
      - $jval / $factor
        * ($ymax - $marginb
          - $margint - $shy)
        / $max,
);
```

It could be an even more refined way to wrap arithmetic operations, if feasible with perltidy.

**Comment by shancock9** [comment]
The default formatting for this is

```
# perltidy
$poly->addPt(
    $marginl + $i * $w - $k - $shx,
    $ymax - $marginb -
      $jval / $factor * ( $ymax - $marginb - $margint - $shy ) / $max,
);
```

It looks like the example is being formatted with something like ``-bbao -l=60``.

It would be difficult to modify line break algorithm for this specific example
without running into problems in other cases, and also changing a lot of
existing formatting.

But note that adding parens around complex terms can sometimes be helpful. For
example

```
#perltidy -bbao -l=60
$poly->addPt(
    $marginl + $i * $w - $k - $shx,
    $ymax - $marginb - (
        $jval / $factor
          * ( $ymax - $marginb - $margint - $shy )
          / $max
    ),
);
```

I find this is a little better than the clang-format because it does not break
the parenthesized expression ``( $ymax - $marginb - $margin1 -$shy )``.

**Comment by Julien-Elie** [comment]
Thanks for the suggestion of additional parentheses.  Adopted!

I've also surrounded the second factor so as to obtain:

```
$poly->addPt(
    $marginl + $i * $w - $k - $shx,
    $ymax - $marginb
      - ($jval / $factor)
      * (($ymax - $marginb - $margint - $shy) / $max),
);
```
