### ISSUE TITLE
Missing checks with --warn-mismatched-returns

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#154]
Trying the new `-wmr` option, it seems that the number of returned values is not always checked:

```
sub f {
    return (1, 2);
}

sub g {
    return (sub { print "ok"; }, sub { print "nok"; });
}

my ($var) = f();
my ($var2) = g();

print $var;
&$var2;
```

Only a warning for the use of `f()` is returned:

```
perltidy -wmr -se test.pl 
test.pl: 2:u:f:2:1:1: fewer than max values wanted at 1 of 1 calls(line 9)
```

**Comment by Julien-Elie** [comment]
Also, another piece of code without any warning:

```
sub h {
    ($_[0] == 1) ? return (1) : return (1, 2);
}

my $var3 = h(2);
print $var3;
```

`perltidy -wmr` reports a warning if I use `my ($var3) = h(2);`
I'm wondering whether it should not also catch a warning without the parentheses?

**Comment by shancock9** [comment]
Thanks for testing this new feature, I really appreciate the feedback. Both of these are interesting
cases.

For the case of the anonymous subs, the coding counting list items was giving up at an anonymous sub,
but it is very easy to handle and will be fixed in the next release.

The other example is more interesting. I would say that the correct result in this case would be
no warning, so the warning with ($var) should not be given. The reason is that this is an example
of a situation where a sub can return a differing number of items, depending on the input
arg values and other state variables. In general we can't know what these are in a static analysis 
(even though it is obvious in this case), so the best we can do is to check that the number of values
wanted is within the range of possible return values, and to bias any uncertainty in favor of not giving
a false warning. In this specific case, this logic would say that we should not flag this as a warning
because the number wanted is between the 1 and 2 possible return values. 

I'll fix this in the next release.

**Comment by Julien-Elie** [comment]
Thanks for your analysis.
OK, I agree with your suggestion of just checking that the number of assigned variables is in the possible values.

Incidentally, maybe it could be checked exactly instead of a min-max range?  For instance, perltidy could return a warning with:

```
sub h {
    ($_[0] == 1) ? return (1) : return (1, 2, 3);
}

my ($var, $var2) = h(2);
```

And why shouldn't a warning be reported with `my $var = h(2)` without any parentheses at all?  It looks like `$var` is assigned the latest returned value.  One may have thought the function always returns a unique value when using that assignment without parentheses, so shouldn't he be warned for it?

Another case:

```
sub f2 {
    (1, 2);
}

my ($var) = f2();
```

There's no warning.  Wouldn't one or both of "x" and "u" warnings be reported?

**Comment by shancock9** [comment]
Checking discrete values, rather than just a range, is a good idea and possible future improvement.
But note that the following example does currently produce a warning because a lower bound of 1 is
treated specially

```
sub h {
    ($_[0] == 1) ? return (1) : return (1, 2, 3);
}

my ($var, $var2) = h(2);
```

For now I plan to just check calls which request lists.

The logic works by checking sub calls requesting a list with a finite number of items, and comparing them to
the number of items in the return statements of called subs.  Testing showed that most difficulties with this
involve cases where both sides of the call had just 0 or 1 items. The rules for handling this still need
some refinement, but the basic idea, to prevent false warnings, is to only give a warning if a list of 2
or more items occurs on one side of the equation or the other. Another problem that came up in testing is
when code relies on the default return mechanism rather than a return.  The analysis will not work in this
case. In general, it is not possible to determine these return values with a static analyis, but in
simple cases it is so I may add a partial workaround in the future.

The example below falls into this second category. Since there is no return, the final ``(1,2)`` is not seen,
and no warning is produced. A warning would be produced if there were a return statement.


```
# no return
sub f2 {
    (1, 2);
}

my ($var) = f2();
```

Thanks again for the suggestions.

**Comment by Julien-Elie** [comment]
Thanks for your detailed answer as usual Steve.
I thought functions without an explicit `return` statement were already handled because with:

```
sub f2 {
    (1, 2);
}

my ($var, $var2) = f2();
```

I obtained:

```
perltidy -wmr -se test.pl
test.pl: 1:x:f2:*:2:2: no return seen; 1 calls(line 5)
```

Incidentally, maybe "call" could be in singular form in the output when there's only one.  Not a big deal, I just noticed!

**Comment by shancock9** [comment]
Will do. I should have a new version which cleans up some of these issues in a couple of weeks.
Thanks for the feedback. I did find a little glitch in the perltidy source by running this analysis, so it
is starting to get useful.

**Comment by shancock9** [comment]
Tagged version 20240511.07 has improved logic for ``--warn-missing-returns``.
The logic is more precise, and requests for scalars are now checked.  Anonymous
subs as list elements are now counted.  The updated list of possible issues is:

```
    x => "want array but no return seen",
    y => "want scalar but no return seen",
    o => "want array with excess count",
    u => "want array with unmatched count",
    s => "want scalar but only arrays with count >1 returned",
```

The main limitation is that it will not be useful for subs which rely
on the default return mechanism, rather than using the ``return`` keyword.

**Comment by Julien-Elie** [comment]
Thanks for your improvements, especially the new `y` check.  Just tested with 20240511.08 and it all looks fine.

**Comment by Julien-Elie** [comment]
FWIW, the new `m` option introduced in 20250311.xx hasn't been documented yet.

**Comment by shancock9** [comment]
Thanks, I've added it.
