### ISSUE TITLE
Preserve function signature on a single line

### ISSUE THREAD

**Issue by atoomic** [perltidy/perltidy#22]
A function signature like this one `sub foo ( $self, $opts = do { ... } ) {` should stay as a single line and do not tidy on multiple lines as it's currently formatted 
```
sub foo ( 
$self, $opts = do { ... } 
) {
```

**Comment by atoomic** [comment]
adding `)` to the do_follower list fixes the issue in Formatter.pm 
but we only need to do it inside a function prototype

**Comment by shancock9** [comment]
Thanks,
Yes, I agree that the prototype shouldn't break and I'll look at this. This is a good start, but I think I see a problem. It can happen that we need to format an entire subroutine that is written in one single very long line. This can happen for example if the subroutine is written by a code generator that uses perltidy to do its formatting. (RPerl does this for example and it caused a problem with the previous release).  So we need to be careful to just do this for the specific prototype paren involved rather than all parens on a line.

I'll look into this.
Thanks again! I appreciate the help.
Steve

**Comment by shancock9** [comment]
I have a fix which seems to be working and gets around the single long line problem. I used the 'weld' feature to weld a closing brace to a following closing prototype paren to keep a line break from putting the prototype paren on a new line. All coding is in one new subroutine which sets a weld flag.
The steps are as follows:

    # 1. look for an opening sub brace,
    # 2. look back one nonblank character for a closing paren [the prototype]
    # 3. if we find one, look back one more character for any closing brace,
    # 4. and if we find one, then set a 'weld' flag to weld the closing brace to the closing
    # paren.

I am going to run some tests.

**Comment by shancock9** [comment]
The fix I wrote works, even for anonymous subs with signatures, so I uploaded it. I will eventually make it  more efficient.

**Comment by atoomic** [comment]
Excellent, the fix is in e9cf334a4b98ecfceec93b27985d0c8320467feb
we can probably close this case?
