### ISSUE TITLE
print statement causes degradation to formatting

### ISSUE THREAD

**Issue by jidanni** [perltidy/perltidy#24]
```
$ echo print if \$x%2|perltidy 
print if $x % 2
$ echo print \$x%2|perltidy 
print $x% 2
```
We see before the operator (% (same with +, etc.)) a space has not been inserted.
perltidy, v20200110

**Comment by jidanni** [comment]
No problem here:
```
echo print 8+2|perltidy
print 8 + 2
```

**Comment by shancock9** [comment]
This is intentional. In older versions of perl, results could depend on the existence of a space after a possible file handle, like $x.  So because the $x follows a 'print', perltidy does not change the space after the $x.

**Comment by jidanni** [comment]
Hmmm, doesn't seem to be mentioned on the man page. Plus there seems to be no flag one can use to tell perltidy that I don't need that behavior anymore.

**Comment by shancock9** [comment]
I will add the following to the docs. Adding a flag to bypass these checks would be foolish.

The various parameters controlling whitespace within a program are requests which perltidy follows as well as possible, but there are a number of situations where changing whitespace could change program behavior and is not done.   Examples are whitespace around bareword symbols and possible filehandles.  For example, consider the problem of formatting the following subroutine:

   sub print_div {
      my ($x,$y)=@_;
      print $x/$y;
   }

Suppose the user requests that / signs have a space to the left but not to the right. Perltidy will refuse to do this, but if this were done the result would be
   
   sub print_div {
       my ($x,$y)=@_;
       print $x /$y;
   }

If formatted in this way, the program will not run (at least with recent versions of perl) because the / is assumed to start a quote. In a complex program, Perl might find a terminating / to the multiline quote and run, but incorrectly.

Similar issues arise with other binary operator symbols, such as + and -, and in older versions of perl there could be problems with ternary operators.  So to avoid changing program behavior, perltidy has the simple rule that whitespace around possible filehandles is left unchanged.  Likewise, whitespace around barewords is left unchanged. But the bigger picture is that it is risky write programs which do math operations involving a term which could be taken to be a filehandle.

**Comment by shancock9** [comment]
perltidy v20200619 adds some documentation on this issue.

**Comment by jidanni** [comment]
> If formatted in this way, the program will not run (at least with recent versions of perl) because the / is assumed to start a quote. In a complex program, Perl might find a terminating / to the multiline quote and run, but incorrectly.

I hope you mention "Due to a bug (#...) in perl, ..." or "Now that perl has fixed bug (#...), ..."

(One might wonder if $/ is safe anymore...)
