### ISSUE TITLE
Prevent execution of BEGIN / INIT / CHECK / UNITCHECK blocks

### ISSUE THREAD

**Issue by HaleTom** [perltidy/perltidy#36]
I want to check my `perl` code without opening myself up for executing code in `BEGIN` / `UNITCHECK` blocks.

[ALE, a `vim` linter, warns the following](https://github.com/dense-analysis/ale/blob/master/doc/ale-perl.txt):

> ALE offers a few ways to check Perl code. Checking code with `perl` is
disabled by default, as `perl` code cannot be checked without executing it.
Specifically, we use the `-c` flag to see if `perl` code compiles. This does
not execute all of the code in a file, but it does run `BEGIN` and `CHECK`
blocks. See `perl --help` and https://stackoverflow.com/a/12908487/406224

[This perlmonks post](https://www.perlmonks.org/?node_id=853778) also shows that `CHECK` and `INIT` blocks can be executed under some circumstances.

How can I check `perl` code without running any of it?

Prior and related art:
* [Same question on StackExchange](https://stackoverflow.com/questions/63741274/prevent-compile-linting-execution-of-begin-unitcheck-blocks)
* [Perl-Critic issue](https://github.com/Perl-Critic/Perl-Critic/issues/924)

**Comment by shancock9** [comment]
I suppose it depends on what you mean by "check".  If we consider for example the 
following program, 'test.pl'

```
BEGIN {
unlink $0;
}
```

You can safely run 

```
perltidy test.pl
```

and it will reformat it and report if there are obvious problems such as missing braces.
So in that sense perltidy can safely do some checking.  Perltidy does not invoke perl.
Long ago, perltidy had an option to do syntax checking by running 'perl -c'. That
was removed for the reasons you mention.

You can also run a tool like perlcritic to check for common problems.

But if you check syntax with perl

```
perl -cw 'test.pl'
```

then perl will report something like:

```
/tmp/check.t syntax OK
```

but the file will have vanished because the BEGIN block was executed.  I don't know of a way to prevent perl from executing a BEGIN block.  Eventually you have to run perl, but it is important to only run scripts you trust, and not to run as root.
