### ISSUE TITLE
system($foo ); Doesn't tidy.

### ISSUE THREAD

**Issue by toddr** [perltidy/perltidy#50]
When I try to tidy this: `system($foo );`, I'd expect it to tidy to `system($foo);` Is this a bug or expected? It seems to have been this way for a while.

**Comment by shancock9** [comment]
This is actually intentional and has always been the behavior.  I
ran a version from 2002 to check this and got the same result.  

This is done out of an over-abundance of caution for the arguments of some
functions, including 'system'.

I have added the following note to the section in the manual titled
"Note1: Perltidy does always follow whitespace controls".

Out of an abundance of caution, arguments of the following builtin
keywords may not respond to the normal spacing controls: print, printf,
sort, exec, system.  If this happens, the spacing will have to be
changed manually.  For example, the space, or lack of space, after the
parameter $foo in the following line will not be changed in formatting.

   system($foo );
   system($foo);
