### ISSUE TITLE
Disable syntax check for certain sections

### ISSUE THREAD

**Issue by ecos-platypus** [perltidy/perltidy#65]
We use a Perl module that extends the Perl syntax. When using perltidy on code sections with the extended syntax, syntax errors are thrown and formatting fails. Wrapping the section within `#<<<` and `#>>>` while using `--format-skipping` sadly doesn't solve the issue.

Could a new flag be added for disabling the syntax errors for certain sections (e.g., by deleting the sections before running the syntax check)? Both new section markers for a new type of section or an addition to the `--format-skipping` sections would be perfectly fine, whatever you prefer.

Example with a syntax error:
```
#<<<
$test -> (
#>>>
```

**Comment by shancock9** [comment]
Basically, it looks like you would like to mark off sections of the input file and have perltidy pass them verbatim, similar to the way it handles sections of 'pod' documentation mixed in with perl code.  This would not be difficult to implement, and would be similar to the --format-skipping option but with a different name, such as --pass-verbatim. It would need to use a different default starting comment to avoid conflicts with the existing --format-skipping flag.  For example, the starting string could be '#<<V', where the V stands for Verbatim: 

```
#<<V
$test -> (
#>>>
```

Whether or not this would solve your particular problem depends on a couple of things. First, this might work if the extended syntax is fairly localized, but if not it can become a burden to put comments in a lot of places.  

Second, the sections which are marked off with these comments should not cause a syntax error when they are hidden from the perltidy tokenization process.  In the above snippet, for example, if there is a closing
paren somewhere in the script which is not in a skipped section, then an error will occur due to unbalanced parens.

**Comment by shancock9** [comment]
The following special version of perltidy (call it _perltidy_hide.pl_ for example) can be used to test this technique to see if it is useful.

```
#!/usr/bin/perl
package main;
use Perl::Tidy;

=pod

Hide sections of as script from perltidy which are between special comments,
like this:

#<<V

anything between '#<<V' and '#>>V' is hidden from perltidy but seen by perl

#>>V

This works by converting #<<V into =pod and $>>V into =cut before
processing, and then converting back after processing.

=cut

my $arg_string = undef;

exit Perl::Tidy::perltidy(
    argv      => $arg_string,
    prefilter => sub {
        $_ = $_[0];
        s/^(#<<V\b.*)$/=pod $1/gm;
        s/^(#>>V\b.*)$/=cut $1/gm;
        return $_;
    },
    postfilter => sub {
        $_ = $_[0];
        s/^=pod (#<<V\b)/$1/gm;
        s/^=cut (#>>V\b)/$1/gm;
        return $_;
    },
);
```

**Comment by zweiter** [comment]
Yeah, this technique would be quite useful indeed. No more `.ERR` files and the code outside the verbatim markers `#<<V` and `#>>V` has been tidied up properly!

**Comment by ecos-platypus** [comment]
Agreed, the technique works like a charm!

**Comment by shancock9** [comment]
Version 20210625 is released and has this option builtin.
