### ISSUE TITLE
--keyword-group-blanks adds spurious blank lines

### ISSUE THREAD

**Issue by scop** [perltidy/perltidy#69]
`--keyword-group-blanks` seems to add spurious blank lines. With current git master:
```perl
package Bug;

use strict;
use warnings;

sub _foo {
    my ( $a, $b, $c ) = @_;

    my $x1;
    my $x2;
    my $x3;
    my $x4;

    return 0;
}

sub _bar {
    my ( $a, $b, $c ) = @_;

    my $x1;
    my $x2;
    my $x3;

    return 0;
}

1;
```

`perltidy --keyword-group-blanks` adds a blank line after `sub _foo {` (but not `sub _bar {`). I've read the doc about `--keyword-group-blanks` and it talks about "placement of blank lines within and around groups of statements". But to me the five `my` lines in `_foo` is not a group of statements, because there is a blank line between the first and the remaining four.

Anyway getting a blank line inserted after the `sub` in the first but not the second looks inconsistent and not nice. (To clarify, would prefer the insertion in the first not to happen.)

**Comment by shancock9** [comment]
There is a parameter --keyword-group-blanks-size=s, -kgbs=s, which has a default setting
of -kgbs=5.  It is counting the number of keywords to decide if the -kgb logic should
apply.  When it counts, it does not count blank spaces (since this control will change
them); it only counts the number of keywords ('my' in this case).  So in the first example
there were 5 'my' lines and -kgb got activated, and in the second case there were
4 'my' lines and the -kgb logic did not get activated.  

So the fix would be to reduce the value of -kgbs.  It is unfortunate
that there is a default value of 5 buried in the manual, but it had to have a
value, and after some testing it seemed that 5 worked as well as any.

But it looks like the manual needs to be clarified about what this number means.
It states that it this number is "the number of consecutive keyword statements"
which is ambigous about whether or not a blank line is counted (they are not).  
I will work on the wording there.

To see why blanks cannot be counted, consider the following:

```
sub _foo {
    my ( $a, $b, $c ) = @_;

    my $x1;

    my $x2;



    my $x3;

    my $x4;

    return 0;
}
```

Running with perltidy -kgb -kgbd -kgbs=5 gives


```
sub _foo {

    my ( $a, $b, $c ) = @_;
    my $x1;
    my $x2;
    my $x3;
    my $x4;

    return 0;
}
```

If blanks had been included in the count for -kgbs it would not have been
possible to reformat this without setting -kgbs=1 and thereby adding blanks 
around every isolated 'my' line in the file.

**Comment by shancock9** [comment]
I'll close this. Some changes were made to the wording in the manual in the last release to try to clarify this.
