### ISSUE TITLE
Assistance with if and comment indentation

### ISSUE THREAD

**Issue by wsnyder** [perltidy/perltidy#72]
I'm setting up perltidy on a 50K line project, and have it mostly consistent with the wanted style except for cases such as these:

```
-        exit $! if $!;  # errno
-        exit $? >> 8 if $? >> 8;  # child exit status
-        exit 255;  # last resort
+        exit $!      if $!;                                       # errno
+        exit $? >> 8 if $? >> 8;                                  # child exit status
+        exit 255;                                                 # last resort

 sub calc {
     my $default = shift;
-    my $ok = max_p();
+    my $ok      = max_p();
```

Where the "-" lines are what I want, and "+" is what perltidy v20200110 gives.

The mismatch is I want 1. single space before if, and 2. two spaces before comments always, 3. single space before/after = (or =>).  All of these seem to be cases where perltidy is trying to line things up between lines, which I don't want (because if a patch modifies one line that can then change many line's indentation).  

I tried -novalign, though the documentation comment about "debug use" was scary, this seemed to solve 1 and 3, but not 2.

Also I'd prefer close parenthesis lined up with the previous block, but can live without a fix if necessary:

```
 compile(
     verilator_flags2 => ["--top-module ${module}"]
-    );
+);
```

Suggestions?  Thanks in advance, and great tool.

These were created with this .perltidyrc file
```
--closing-token-indentation=1
--cuddled-else
--fixed-position-side-comment=0
--freeze-newlines  # do not redo line breaks
--maximum-line-length=99
--minimum-space-to-comment=2
--noadd-newlines
--noblanks-before-comments
--nohanging-side-comments
--nooutdent-long-lines
--opening-brace-always-on-right
--paren-tightness=2
--stack-opening-tokens
--standard-error-output  # errors to standard error output
--warning-output
```

**Comment by shancock9** [comment]
I made a patch in the development version which should stop side comment alignments when the -novalign flag is set.  It was a simple fix.  The next release to CPAN will be about 1 Oct, but if you want to experiment with this updated version you can get version 20200717.02 at https://github.com/perltidy/perltidy/releases.  With this patch, the side comments should obey your -minimum-space-to-comment=2 flag.

So if the patch I made works, it looks like the -novalign flag will resolve most of the issues.

I will update the manual to clarify the -novalign flag.  It was added to assist debugging but it is safe to use and is routinely tested when updates are made.  All it does is output lines one-by-one instead of collecting them into groups for vertical alignment.

The last issue, regarding alignment of closing parentheses, gets into some complicated issues.  I'll look at it but doubt that I can do anything by the next release.

**Comment by wsnyder** [comment]
Great, thanks, that seems to do what I want.  Don't worry about the ); issue if there isn't a setting for that, I'll adapt.

**Comment by shancock9** [comment]
You might see if --closing-token-indentation=2 is closer to what you want.

**Comment by wsnyder** [comment]
Bingo!
