### ISSUE TITLE
Custom subs with (&@) prototype impossible to configure?

### ISSUE THREAD

**Issue by bbrtj** [perltidy/perltidy#77]
I've been struggling with prototyped subs for some time. The problem occurs with most of `List::Util` functions (`any, first, reduce` etc), but also with others like `Test::Exception` (`lives_ok, dies_ok`). I would like to make them behave exactly like `map` and `grep`. I've been using `-sal='first any sum sum0 reduce'` for this, which helps a little bit with the indentation, but the result is still far from perfect.

Input:
```
any { $_ } 1 .. 10;

grep { $_ } 1 .. 10;

any {
	$_
} 1 .. 10;

grep {
	$_
} 1 .. 10;
```
Output:
```
any { $_ }
	1 .. 10;

grep { $_ } 1 .. 10;

any {
	$_;
	}
	1 .. 10;

grep {
	$_
} 1 .. 10;
```

Full config:
```
### GENERAL
--maximum-line-length=120
--converge

### WHITESPACE
--tabs
--entab-leading-whitespace=4
--continuation-indentation=4
--extended-continuation-indentation
--no-delete-old-newlines

### ALIGNMENT
--no-outdent-long-lines
--no-outdent-labels
--novalign
--no-logical-padding

### TIGHTNESS
--opening-sub-brace-on-new-line
--square-bracket-tightness=2
--paren-tightness=2
--brace-tightness=2
--opening-token-right
--one-line-block-nesting=1

-sal='first any sum sum0 reduce'
```

I tried using `--one-line-block-nesting=1` but that only helps when the expression is fully in one line. I searched the docs many times but couldn't find a solution. Maybe there is one already?

Obviously examining function prototypes requires looking into imported packages, but for me it would be enough to have a config like `-sal` which would make perltidy treat these keywords like `grep`

**Comment by shancock9** [comment]
Yes, this seems like a useful feature, and I don't see a way to do it currently.  In the perltidy code, the behavior of map grep sort and sometimes eval is controlled by a couple of simple hashes which currently just contains those key words.  As a test, I added 'any' and it then formatted like grep.  So this looks like an easy update - an input parameter is just needed to add new words to these hashes.  Maybe '--grep-alias-list=s', to following along the lines of --sub-alias-list=s.

**Comment by shancock9** [comment]
A parameter to do this, -gal=s, will be in the next release, which is probably a couple of months away. If needed sooner, the parameter is working in the tagged development version 20211029.04 at

https://github.com/perltidy/perltidy/tags


Preliminary documentation is as follows:

=item B<-gal=s>,   B<--grep-alias-list=s>

This flag causes a code block following a specified word to be formatted as if it followed the keyword 'grep' (or 'map' or 'sort').  The string B<s> contains one or more such alias words, separated by spaces or commas.

This allows code block arguments to external list operator functions to be formatted in the same way as code blocks which follow the perl builtin keywords 'grep', 'map', and 'sort'.  By 'list operator' is meant a function which is invoked in the form

      word {BLOCK} @list

Perltidy tries to keep code blocks for these functions intact, since they are usually short, and does not automatically break after the closing brace since a list may follow. It also does some special handling of continuation indentation.

For example, the code block arguments to functions 'My_grep' and 'My_map' can be given formatting like 'grep' with

        perltidy -gal='My_grep My_map'

By default, the following list operators in List::Util are automatically included:

      all any first none notall reduce reductions

Any operators specified with B<--grep-alias-list=s> are added to this list.
The next parameter can be used to remove words from the default list.

=item B<-gaxl=s>,   B<--grep-alias-exclusion-list=s>

The B<-gaxl=s> flag provides a method for removing any of the default list operators given above
by listing them in the string B<s>.  To remove all of the default operators use B<-gaxl='*'>.

**Comment by bbrtj** [comment]
Thank you for the implementation @shancock9, much appreciated!

**Comment by shancock9** [comment]
Version 20220217 has been released with this new control.
