### ISSUE TITLE
Finer grain for vertical alignment configuration

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#79]
Would it be possible to distinguish the several kinds of vertical alignments?
For instance to allow vertical alignment only for a few constructions, like hashes definitions (aligned on `=>`) but not on variable declarations.

**Comment by shancock9** [comment]
This has been requested in the past, and I worked on it but encountered significant difficulties because many of the alignment rules are inter-related. Simply removing one type of alignment can lead to problems with other types. I think it can eventually be done, but it is a little complicated and for now the main options are either to use the -novalign flag to turn off vertical alignment or to insert blank lines to break occasional bad alignments.  Also, specific cases of poor alignments can sometimes be fixed by adjusting alignment rules.

**Comment by Julien-Elie** [comment]
Thanks for your comment.  I understand it is complicated.  Maybe all kinds of alignment should not be separated and configurable, but only a few ones (those that have been requested in the past for instance).  Subsets could perhaps be found depending on the level of inter-relation in perltidy code.
At least it would be interesting for hashes definitions: they are pretty more readable when aligned.

**Comment by shancock9** [comment]
I took another look and found a way around the problems that I hit previously.  It was a matter of adding the controls as late as possible in the formatting process, rather than as early as possible. The next release will have detailed vertical alignment control.  The release to CPAN is about two months away, but this feature is in development version 20211029.05 at

https://github.com/perltidy/perltidy/tags

The description is as follows

### **Finer alignment control with --valign-exclusion-list=s or -vxl=s and --valign-inclusion-list=s or -vil=s**

More detailed control of alignment types is available with these two
parameters.  Most of the vertical alignments in typical programs occur at one
of the tokens ',', '=', and '=>', but many other alignments are possible and are given in the following list:

    = **= += *= &= <<= &&= -= /= |= >>= ||= //= .= %= ^= x=
    { ( ? : , ; => && || ~~ !~~ =~ !~ // <=> ->
    if unless and or err for foreach while until

These alignments are all enabled by default, but they can be selectively disabled by including one or more of these tokens in the space-separated list **valign-exclusion-list=s**.  For example, the following would prevent alignment at **=** and **if**:

    --valign-exclusion-list='= if'

If it is simpler to specify only the token types which are to be aligned, then use the special symbol **\*** for this exclusion list and include the types which are to be aligned in the list of **--valign-inclusion-list** (this works because **\*** is not one of the alignment tokens). For example,
the following parameters enable alignment only at commas and 'fat commas':

    --valign-exclusion-list='*'
    --valign-inclusion-list=', =>'

These parameter lists should consist of space-separated tokens from the above
list of possible alignment tokens.  If an unrecognized parameter appears, it is
simply ignored. And if a parameter is entered in both lists by mistake
then the exclusion list has priority.

The default values of these parameters enable all alignments and are equivalent to

    --valign-exclusion-list=' '
    --valign-inclusion-list='*'

To illustrate, consider the following snippet with default formatting

    # perltidy
    $co_description = ($color) ? 'bold cyan'  : '';           # description
    $co_prompt      = ($color) ? 'bold green' : '';           # prompt
    $co_unused      = ($color) ? 'on_green'   : 'reverse';    # unused

To exclude all alignments except the equals we could use:

    # perltidy -vxl='*' -vil='='
    $co_description = ($color) ? 'bold cyan' : '';          # description
    $co_prompt      = ($color) ? 'bold green' : '';         # prompt
    $co_unused      = ($color) ? 'on_green' : 'reverse';    # unused

To exclude only the equals we could use:

    # perltidy -vxl='='
    $co_description = ($color) ? 'bold cyan' : '';     # description
    $co_prompt = ($color) ? 'bold green' : '';         # prompt
    $co_unused = ($color) ? 'on_green' : 'reverse';    # unused

Notice in this last example that although only the equals alignment was
excluded, the ternary alignments were also lost.  This happens because the
vertical aligner sweeps from left-to-right and usually stops if an important
alignment cannot be made for some reason. 

But also notice that side comments remain aligned because their alignment is
controlled separately with the parameter **--valign-side\_comments** described above.

**Comment by Julien-Elie** [comment]
That's pretty great news Steve, thanks!
I think `--valign-exclusion-list='*' --valign-inclusion-list='=>'` will precisely answer the feature request of this report.
I'll also give a try to the inclusion of the comma `,` as suggested in one of the example to see how the resulting code looks like.  I'll try your 20211029.05 version and tell you soon.

**Comment by rra** [comment]
Oh, wow, this is great, thank you so much!

**Comment by Julien-Elie** [comment]
I've just tested the 20211029.05 version with `--valign-exclusion-list='*' --valign-inclusion-list='=>'`.
I confirm it totally responds to that report.  Thanks!

**Comment by Julien-Elie** [comment]
Would it be complicated to align the last two `=>` with the first?

```
            '<anywhere>' => {     
                'comment'         => 'string',
                'max-connections' => 'number / "unlimited" / "none"',
                'streaming'       => 'boolean',
            },
            'group' => {},
            'peer'  => {},
```


and have a better alignment of `=>` as well as comments in the following piece of code.
(yes, I understand it is fairly complicated, but maybe `# useful?` and `# not checked` could be aligned, and more `=>` too?)

```
my %type_regex = (
    'boolean' => '^(?:true|false)$',    # innfeed.conf doesn't allow other
    'floating-point number'             => '^\d+\.\d+$',    # no exponents
    'floating-point number (0.0-100.0)' =>
      '^(?:100\.0+|\d{1,2}\.\d+)$',                         # no exponents
    'hostname'                     => '^' . $hostnameRE . '$',
    'IPv4 address / "any / "none"' => '^(?:' . $ipv4 . '|any|none)$',
    'IPv6 address / "any / "none"' => '^(?:' . $ipv6 . '|any|none)$',
    'list of hostnames'            => '^'
      . $hostnameRE
      . '(?:\s*,\s*'
      . $hostnameRE . ')*$',
    'list of hostnames or netblocks' => '^'
      . $hostblockRE
      . '(?:\s*,\s*'
      . $hostblockRE . ')*$',
    'minsize[,maxsize] definition' => '^\d+(?:,\d*)?$',
    'mintime[,maxtime] definition' =>
      '^(?:\d+[Mdhms])+(?:,(?:\d+[Mdhms])*)?$',
    'number'                           => '^\d+$',
    'number / "unlimited" / "none"'    => '^(?:\d+|unlimited|none)$',
    'path'                             => '.*',                       # useful?
    'set of access permission letters' => '^[RPIANL]+$',
    'string'                           => '.*',    # not checked
);
```

**Comment by shancock9** [comment]
On the first question, there is a firm rule that vertical alignments of code cannot continue across code blocks, or any change in level.  This is really important for avoiding bad alignments, so it cannot be changed

On the second question, the vertical alignments in the example are being limited by the line length (set with -l=n, where n=80 by default). Here is what the example looks like with -l=120 and -iscl, for example.  The -iscl flag says to ignore the length of side comments when limiting by line length.  Otherwise, a long side comment like the first one in the example might not align.

```
# perltidy -l=-l=120 -iscl
my %type_regex = (
    'boolean'                           => '^(?:true|false)$',                                         # innfeed.conf doesn't allow other
    'floating-point number'             => '^\d+\.\d+$',                                               # no exponents
    'floating-point number (0.0-100.0)' => '^(?:100\.0+|\d{1,2}\.\d+)$',                               # no exponents
    'hostname'                          => '^' . $hostnameRE . '$',
    'IPv4 address / "any / "none"'      => '^(?:' . $ipv4 . '|any|none)$',
    'IPv6 address / "any / "none"'      => '^(?:' . $ipv6 . '|any|none)$',
    'list of hostnames'                 => '^' . $hostnameRE . '(?:\s*,\s*' . $hostnameRE . ')*$',
    'list of hostnames or netblocks'    => '^' . $hostblockRE . '(?:\s*,\s*' . $hostblockRE . ')*$',
    'minsize[,maxsize] definition'      => '^\d+(?:,\d*)?$',
    'mintime[,maxtime] definition'      => '^(?:\d+[Mdhms])+(?:,(?:\d+[Mdhms])*)?$',
    'number'                            => '^\d+$',
    'number / "unlimited" / "none"'     => '^(?:\d+|unlimited|none)$',
    'path'                              => '.*',                                                       # useful?
    'set of access permission letters'  => '^[RPIANL]+$',
    'string'                            => '.*',                                                       # not checked
);
```

**Comment by Julien-Elie** [comment]
Many thanks for your valuable answers that help understanding better how perltidy works.  Greatly appreciated.

Thanks again for your new flags `--valign-exclusion-list='*' --valign-inclusion-list='=>' `which I confirm work fine.  I've just reformatted the Perl scripts we have in the news server INN (https://github.com/InterNetNews/inn/commit/e8d1e6e7eeace92bf0760611dd9f09122a3bd1d9) and I am happy with the result.  (I've just asked here the few nits I've spotted, but they sound normal after all.)

**Comment by Julien-Elie** [comment]
With the release of Perltidy 20220217, I believe this issue can now be closed.
The new `--valign-inclusion-list='=>'` flag works great.
Thanks again!

**Comment by shancock9** [comment]
I'm very glad I was able to help, and that you were able to get your project reformatted.  I had this option on my 'todo' list for a long time.  I don't know if you noticed, but I made the `--valign-exclusion-list=\*` optional if you enter a `--valign-inclusion-list`, since nothing else really makes sense.  The final man page reads:

If it is simpler to specify only the token types which are to be aligned, then include the types which are to be aligned
in the list of --valign-inclusion-list.  You may leave the valign-exclusion-list undefined, or use the special symbol \*
for the exclusion list.  For example, the following parameters enable alignment only at commas and 'fat commas':

             --valign-inclusion-list=', =>'
             --valign-exclusion-list='*'     ( this is optional and may be omitted )

**Comment by Julien-Elie** [comment]
Hi Steve, yes I noticed it when reading CHANGES:

`For example, -vil='=>' means just align on '=>'.`

I asked myself why the exclusion list was not mentioned, so I tried, and it worked :)
I removed the exclusion list this morning from the `.perltidyrc` file ( https://github.com/InterNetNews/inn/commit/f0774126316ccf3b5832b6b10a7f4bb6329fe3ad).

Many thanks for pointing that out in case I did not notice!
