### ISSUE TITLE
Warning when outdenting comments and quotes

### ISSUE THREAD

**Issue by Julien-Elie** [perltidy/perltidy#81]
When a comment exceeds the maximum line length and is outdented (which is the default), couldn't perltidy emit a warning to inform the user? (when `-w` is on for instance)

It could also warn for long quotes.

As perltidy does not reflow comments and quotes, I think it could be a worthwhile feature so that the user manually has a look and reflows himself these long lines.

**Comment by shancock9** [comment]
The log file, which can be produced with the ```-g``` flag, has relevant information at its tail end. It looks like this:


```
43 long lines were outdented:
  First at output line 2
   Last at output line 201
  use -noll to prevent outdenting, -l=n to increase line length

14 output lines exceeded 60 characters:
 First at line 11 by 8 characters
 Maximum at line 29 by 11 characters
 Last at line 201 by 8 characters
```

It wouldn't be possible for perltidy to automatically reflow comments and quotes because they may contain spaces and line breaks which are significant. But there is an interactive program distributed with perltidy in the examples folder called 'perlcomment.pl' which might be useful. It steps through block comments and offers to reformat them with Text::Autoformat.

**Comment by Julien-Elie** [comment]
Thanks for the hint for `-g`.
There might be an issue in the reported count, though:

```
2 long lines were outdented:
  First at output line 414
   Last at output line 414
```

It should have returned only 1 long line.

**Comment by shancock9** [comment]
Thanks, it will be fixed in the next release.

**Comment by Julien-Elie** [comment]
I confirm the reported numbers are now right in Perltidy 20220217.
